# Generated by Django 2.0.3 on 2021-02-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentIdeaFac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('userid', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('confirmpassword', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FovouriteFac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='NewIdeaFac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('uploadpic', models.ImageField(upload_to='pic_folder/')),
                ('content', models.CharField(max_length=250)),
                ('dateofpublish', models.CharField(default='2020', max_length=4)),
                ('dateandtime', models.DateTimeField(default='2020-12-12 10:00:00')),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('votes', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='fovouritefac',
            name='newideaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.NewIdeaFac'),
        ),
        migrations.AddField(
            model_name='commentideafac',
            name='facultyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty'),
        ),
        migrations.AddField(
            model_name='commentideafac',
            name='newideaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.NewIdeaFac'),
        ),
    ]
